---
version: '3.7'
services:
  bot:
    container_name: bot
    build: 
      context: .
    ports:
      - 3000:3000
    restart: always
    env_file: 
      - .env
    # Map in source and node modules to trigger application restart when it's in watch mode 
    #volumes:
      #- .:/usr/src/app
      #- /usr/src/app/node_modules